"use client";

/* -------------------------------------------------------------------------- */
/*                             External Dependency                            */
/* -------------------------------------------------------------------------- */

import type React from "react";
import { X } from "lucide-react";
import { Controller, type SubmitHandler, useForm } from "react-hook-form";
import type * as z from "zod";
import { zodResolver } from "@hookform/resolvers/zod";

/* -------------------------------------------------------------------------- */
/*                             Internal Dependency                            */
/* -------------------------------------------------------------------------- */

import { otpSchema } from "@/lib/validations";
import { Button } from "@/components/common/button";
import { OtpInput } from "@/components/common/otp-input";
import { InputErrorMessage } from "@/components/common/InputErrorMessage";
import { Spinner } from "@/components/common/loader";

type OtpFormValues = z.infer<typeof otpSchema>;

export const TwoFAInputModal = ({
	isLoading,
	type,
	onComplete,
	close,
	className,
}: {
	isLoading: boolean;
	type?: string;
	className?: string;
	onComplete: (otp: string) => void;
	close: () => void;
}): React.JSX.Element => {
	const {
		handleSubmit,
		formState: { errors },
		control,
	} = useForm<OtpFormValues>({
		resolver: zodResolver(otpSchema),
	});

	const onSubmit: SubmitHandler<OtpFormValues> = async ({ otp }) => {
		onComplete(otp);
	};

	return (
		<div
			className={`relative mx-auto flex h-full max-h-[484px] w-full max-w-[448px] flex-col gap-4 overflow-hidden rounded-2xl border
				border-line bg-white shadow ${className}`}
		>
			<div className="flex w-full flex-col items-center rounded-2xl border p-6 text-center">
				<div className="flex w-full flex-col gap-4">
					<div className="flex flex-row justify-between">
						<h3 className="text-lg font-bold">{type === "email" ? "Email OTP" : "Authenticator App"}</h3>
						<button
							className="z-10 flex h-6 w-6 items-center justify-center rounded-full border border-body duration-200 hover:border-body
								hover:text-body"
							onClick={() => {
								close();
							}}
							type="button"
							aria-label="Close"
						>
							<X size={16} strokeWidth={2} />
						</button>
					</div>
					<p>
						Enter the 6 digit code{" "}
						{type === "email" ? `Sent to your email` : "generated by your Authenticator app"}
					</p>
				</div>

				<form className="flex w-full flex-col gap-2" onSubmit={handleSubmit(onSubmit)}>
					<div className="relative mx-auto my-4 flex flex-col">
						<Controller
							name="otp"
							control={control}
							render={({ field: { onChange, value } }) => (
								<OtpInput value={value} onChange={onChange} numInputs={6} />
							)}
						/>
						<div className="my-2 flex justify-center text-center">
							<InputErrorMessage message={errors.otp?.message} />
						</div>
					</div>
					<div className="flex">
						<Button
							type="submit"
							className="h-[51px] justify-center"
							disabled={isLoading}
							fullWidth
							variant="primary"
						>
							{isLoading ? <Spinner /> : "Withdraw"}
						</Button>
					</div>
				</form>
			</div>
		</div>
	);
};
