export const ENVS = {
	NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
	NEXT_PUBLIC_SOCKET_URL: process.env.NEXT_PUBLIC_SOCKET_URL,
	NEXT_PUBLIC_AUTH_TOKEN_KEY: process.env.NEXT_PUBLIC_AUTH_TOKEN_KEY,
	NEXT_PUBLIC_NODE_ENV: process.env.NEXT_PUBLIC_NODE_ENV,
	NEXT_PUBLIC_API_KEY: process.env.NEXT_PUBLIC_API_KEY,
	NEXT_PUBLIC_API_ID: process.env.NEXT_PUBLIC_API_ID,
	isProduction: String(process.env.NEXT_PUBLIC_NODE_ENV) === "production" || false,
};
